### ISSUE TITLE
Node version mismatch

### ISSUE THREAD

**Issue by thetre97** [anywhichway/dexterous#2]
I'm trying to install this module, but am failing because of node version mismatches. 

I am using v10.6.0, but wsfetch requires 7.6.0. So I install v7.6.0 - but dexterous requires 10.0.0.

Can wsfetch be updated?

**Comment by anywhichway** [comment]
@thetre97 I am not sure what you would like us to do since we don't control wsfetch. Do you mean you wish us to update the version of wsfetch specified in the dexterous package.json file? We have wsfetch working in a v10.*.* environment. The dexterous package is working on our test machines, which are now at v10.6.0 also.

**Comment by thetre97** [comment]
Ah okay, sorry.
I just assumed you did since it is under the same namespace. (https://github.com/anywhichway/wsfetch)

I will raise a PR in that repo.

**Comment by anywhichway** [comment]
@thetre97 engine ref updated.

**Comment by thetre97** [comment]
No worries, thanks @anywhichway  :+1:
